# Generated by Django 4.0.7 on 2022-12-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_researcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='researcher_register',
            new_name='researcher_regilog',
        ),
    ]
