# Generated by Django 4.0.7 on 2022-12-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
