# Generated by Django 4.0.7 on 2022-12-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.PositiveIntegerField()),
                ('birthdate', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('guardianname', models.CharField(max_length=100)),
                ('parentsnumber', models.PositiveIntegerField()),
                ('guardiannumber', models.PositiveIntegerField()),
                ('guardianrelationship', models.CharField(max_length=250)),
            ],
        ),
    ]
