# Generated by Django 4.0.7 on 2022-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_basic_details_marriedstatus_basic_details_spousename'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstcheckup', models.CharField(max_length=10)),
                ('othertest', models.CharField(max_length=10)),
                ('symptoms', models.CharField(max_length=200)),
                ('multiple', models.CharField(max_length=300)),
                ('genetic', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('tobacco', models.CharField(max_length=10)),
                ('alcohol', models.CharField(max_length=10)),
                ('surgical', models.CharField(max_length=10)),
                ('surgicalmessage', models.CharField(max_length=200)),
            ],
        ),
    ]
