# Generated by Django 4.0.7 on 2022-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldetails',
            name='algeric',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='digestive',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='kord',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
