# Generated by Django 4.0.7 on 2022-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_medicaldetails_algeric_medicaldetails_digestive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldetails',
            name='disease',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
