# Generated by Django 4.0.7 on 2022-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_remove_medicaldetails_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='pat_sym',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
