# Generated by Django 4.0.7 on 2022-12-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_basic_details_pat_sym'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='showData',
            field=models.BooleanField(default=False),
        ),
    ]
