# Generated by Django 4.0.7 on 2023-01-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_basic_details_showdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
    ]
