# Generated by Django 4.0.7 on 2023-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_upload_email_upload_name_alter_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='phonenumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
