# Generated by Django 4.0.7 on 2023-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_alter_basic_details_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='guardiannumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='parentsnumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='postal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
