# Generated by Django 4.0.7 on 2023-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_upload_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='key',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
