# Generated by Django 4.0.7 on 2023-02-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_upload_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Encryptedimage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
