# Generated by Django 4.0.7 on 2023-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0018_upload_encryptedimage_alter_upload_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Encryptedimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
