# Generated by Django 4.0.7 on 2023-02-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0019_alter_upload_encryptedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='pdfimage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
