# Generated by Django 4.0.7 on 2023-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0020_upload_pdfimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Decryptedimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
